### PR TITLE
Change format to fit new yaml config files since Tutor 14 and Nutmeg.

### PR DESCRIPTION
**Pull request by angonz**
Change the format of the openedx-auth patch to fit the new yaml config files used since Tutor 14 and Nutmeg.
The old format caused a corrupt lms.env.yml config file.

### CODE REVIEW

**Comment by erickhgm** [comment]
We already had a PR for this: #48

**Comment by fghaas** [comment]
> We already had a PR for this: #48

@angonz Please see the comment I just added on that PR.

**Comment by angonz** [comment]
Ok! In the meantime we will use our fork until the new version is released.

**Comment by fghaas** [comment]
@angonz Taking the liberty from that comment thread:

> If you need this plugin for Nutmeg *now,* please consider sending a PR covering the v0→v1 API transition.

Would you like to have a go at that?

(another courtesy tag for @regisb here)

**Pull request closed without merging**
