### PR TITLE
chore: bump supported tutor versions to work on tutor 18 for redwood

### PR DESCRIPTION
**Pull request by kaustavb12**
## Description

Add support for tutor 18 (Redwood)

## Other information

Private Ref : OpenCraft Internal ticket [BB-8942](https://tasks.opencraft.com/browse/BB-8942)

### CODE REVIEW

**Comment by fghaas** [comment]
@kaustavb12 Please note that we won't merge this until (a) Tutor 18 is out, and (b) you or someone else tests and confirms that this plugin does work with Tutor 18.

Rationale: with Tutor 17, we had a similar "chore" PR (#66), which resulted in subsequent breakage that had to be separately fixed (#70), and we'd like to avoid that this time around.

**Comment by kaustavb12** [comment]
@fghaas

Ack !! I marked it as draft pending verification that it works correctly.
I am currently in the process of deploying redwood sandboxes for testing.

**Comment by tecoholic** [comment]
@kaustavb12 I have done a basic sanity check as a part of the testing Grove for Redwood support. I uploaded a couple of files in the studio and generated the profile data as mentioned in the PR https://github.com/hastexo/tutor-contrib-s3/pull/70. I didn't encounter any issues. Just adding it here, in case you are planning more extensive tests later.

**Comment by gabor-boros** [comment]
@fghaas FYI about the latest comment

**Comment by kaustavb12** [comment]
Thanks a lot @tecoholic 

@fghaas This PR branch has been in use to spin-up a number of sandboxes for Axim in the last month, and no issue has been reported so far. Are we good to merge this ?

I could spin up a sandbox and share the links here if that would help.

cc. @gabor-boros

**Comment by fghaas** [comment]
> @fghaas This PR branch has been in use to spin-up a number of sandboxes for Axim in the last month, and no issue has been reported so far. Are we good to merge this ?

I think so, but we were still waiting for you to mark this PR as Ready for review. :)

**Comment by kaustavb12** [comment]
@fghaas Oops .. sorry about that :smile:

**Comment by fghaas** [comment]
@kaustavb12 I'm a little stumped by the fact that GitHub is apparently waiting for the checks to complete, but they never ran, and I seem to have to way to retrigger them.

Can I ask for a favour? Could you please run (in your local checkout of this topic branch)

```bash
git commit --amend --no-edit
git push --force-with-lease
```

That way we'll hopefully coax GitHub Actions into rescheduling the workflow.

**Comment by kaustavb12** [comment]
@fghaas Force pushed. It says waiting for approval from a maintainer to run the workflow.

**Comment by fghaas** [comment]
> @fghaas Force pushed. It says waiting for approval from a maintainer to run the workflow.

Yes, that bit is expected. I've cleared the workflow to run now.

**Comment by fghaas** [comment]
@mrtmm, this PR is now no longer a Draft, and all checks pass. Please review and merge at your convenience.

**Review by mrtmm — APPROVED** [review]
Ack, thanks!

**Pull request merged**
