### PR TITLE
feat: allows configuring AWS_QUERYSTRING_AUTH

### PR DESCRIPTION
**Pull request by viadanna**
## Description

The changes included in this pull request allow configuring  `AWS_QUERYSTRING_AUTH: false` while keeping the default behavior of `AWS_QUERYSTRING_AUTH: true`

## Testing instructions

1. Setup a new instance using this branch of the plugin
2. Add `S3_QUERYSTRING_AUTH: false` to the instance `config.xml`
3. Deploy the instance
4. Check URLs are generated without authentication signature
5. Set the AWS bucket as public
6. Ensure the S3 object URLs generated by the platform are working

### CODE REVIEW

**Comment by fghaas** [comment]
@viadanna Thanks for the PR. Can you explain what would be the rationale for globally disabling querystring auth (and therefore, requiring essentially all your buckets to be configured with a public ACL, if I understand correctly)? I fear you would be opening yourself up to PII leaks: consider the fact that, for example, a grade report created from the Instructor tab contains learner's email addresses. If you make your bucket public, that information becomes available to anyone with the link to the grade report. Why would you want to do that?

**Comment by viadanna** [comment]
> @viadanna Thanks for the PR. Can you explain what would be the rationale for globally disabling querystring auth (and therefore, requiring essentially all your buckets to be configured with a public ACL, if I understand correctly)? I fear you would be opening yourself up to PII leaks: consider the fact that, for example, a grade report created from the Instructor tab contains learner's email addresses. If you make your bucket public, that information becomes available to anyone with the link to the grade report. Why would you want to do that?

@fghaas This came from testing an XBlock that doesn't support S3 auth yet.

While not safe for a production environment, it has no risks for me for being used in a development environment without real user data, so the bucket can be made public.

I understand this carries risks and the ideal solution would be having the XBlock implement S3 auth, which is expected soon, but it seemed to me that making this configurable could be useful for others too.

**Comment by fghaas** [comment]
> This came from testing an XBlock that doesn't support S3 auth yet.

Okay, can you please point me to the repo of the XBlock you are working on, so we can see how you're planning to use globally-public S3?

**Comment by fghaas** [comment]
Closing this one due to lack of replies. If you still think making this setting configurable is indispensable, please comment here and we'll reopen this PR. Thanks!

**Pull request closed without merging**
