### PR TITLE
chore: bump supported tutor versions to work on tutor 19 for sumac

### PR DESCRIPTION
**Pull request by kaustavb12**
## Description

Add support for tutor 19 (Sumac)

## Other information

Private Ref : OpenCraft Internal ticket [BB-9353](https://tasks.opencraft.com/browse/BB-9353)

### CODE REVIEW

**Comment by kaustavb12** [comment]
@fghaas FYI, similar to Redwood, creating this draft PR to add support for tutor 20. Will deploy and test this in sandboxes.

**Review by mrtmm — COMMENTED** [review]
This looks good to me, @fghaas any objections for merging this?

**Comment by fghaas** [comment]
No objections from my end.

**Review by fghaas — APPROVED** [review]

**Comment by kaustavb12** [comment]
@mrtmm @fghaas Thanks for merging the PR.

**Pull request merged**
