### PR TITLE
remove quotes

### PR DESCRIPTION
**Pull request by lpm0073**
the wrapped quotes in tutors3/patches/openedx-auth don't work with tutor v14.x. they additionally break command line utilities like yq. This PR removes the full quotes from the three keys.

### CODE REVIEW

**Comment by erickhgm** [comment]
Now Tutor is using a YAML file, not a JSON file anymore.
We have break changes with this, those who use it will need to upgrade Open edX to Nutmeg.

Changes: [14.0.0](https://github.com/overhangio/tutor/blob/c4388e134ca4bf1961b9906dd3fb8600d197f7a5/CHANGELOG.md?plain=1#L25)

**Comment by fghaas** [comment]
Just a note here: in addition to the configuration file format changes, Tutor also introduced the v1 plugin API just before the Open edX Nutmeg / Tutor 14 release. I see little point in plugin authors rewriting their plugins _twice_ (once to accommodate the v1 API, and once to accommodate the change in configuration format for Nutmeg), and besides it would also be rather confusing for plugin users to understand which version of a plugin supports what.

Thus, the v0 API version of this plugin will support Maple, and we won't pull Nutmeg-enabling patches into it. The first release of this plugin to support the v1 plugin API, will also support Nutmeg.

Rewriting our plugins for the v1 API is currently on our to-do list, and we'll be tackling them one by one. We have no expectations that any plugin user will be doing the v1 API rewrite for us, but if you need this plugin for Nutmeg *now*, please consider sending a PR covering the v0→v1 API transition. Thank you!

Courtesy tag for @regisb for awareness.

**Comment by gabor-boros** [comment]
@fghaas as I can see the Plugin v1 API is [already supported](https://github.com/hastexo/tutor-contrib-s3/commit/981accd6fce657466565829ef1260672320bae03). This means if @lpm0073 rebases his PR onto the `main` branch, the plugin would support Nutmeg. Am I right or missing something?

**Comment by gabor-boros** [comment]
@fghaas FTR: The changes seems to work as expected.

**Review by foadlind — CHANGES_REQUESTED** [review]
@lpm0073 this looks good in general. Thanks @gabor-boros for testing this. There are some  things remaining before we can merge this:

1. Rebase on latest `main`,
2. Squash the commits and add a commit message based on [the commit message guidelines](https://github.com/hastexo/tutor-contrib-s3/blob/main/HACKING.md#commit-messages). 
3. Add a line in [CHANGELOG.md](https://github.com/hastexo/tutor-contrib-s3/blob/main/CHANGELOG.md) (similar to [this](https://github.com/hastexo/tutor-contrib-s3/pull/51/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)).

**Comment by fghaas** [comment]
PR superseded by #56 (see @foadlind's earlier comment).

**Pull request closed without merging**
